service: real-time-chat-aws
app: real-time-chat-aws
org: lucasfdsilva

provider:
  name: aws
  stage: dev
  region: eu-west-1
  runtime: nodejs12.x

functions:
  connect:
    role: arn:aws:iam::446318123031:role/real-time-chat-aws-connect-lambda
    handler: src/connectHandler.connect
    events:
      - http:
          path: /connect
          method: get

resources: # CloudFormation template syntax
  Resources:
    connectionTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: connectionTable
        AttributeDefinitions:
          - AttributeName: user_id
            AttributeType: S
          - AttributeName: date
            AttributeType: S
        KeySchema:
          - AttributeName: user_id
            KeyType: HASH
          - AttributeName: date
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
